### PR TITLE
Create john_berryman.qmd

### PR DESCRIPTION
**Pull request by sharmachaitanya945**
Got to know about this from upwork  changed according to the video provided in loom and used chatgpt and own python scripts and api to get the transcript changed it to the format in given video so hope it is to your liking
-- greetings 
Chaitanya Sharma 

PS
Not hired by you on upwork yet so just take it as sample work

### CODE REVIEW

**Comment by hamelsmu** [comment]
cc: @amqdn perhaps you can do another video instead

**Comment by hamelsmu** [comment]
Thank you @sharmachaitanya945 please message me on upwork so I can send you a contract for more videos

**Comment by sharmachaitanya945** [comment]
Yes @hamelsmu sir messaging you ASAP

**Comment by hamelsmu** [comment]
Actually @amqdn seems like this PR was incomplete and only included chapter timestamps up until the 10 minute mark.  Perhaps you want to complete this PR so go ahead.

**Comment by sharmachaitanya945** [comment]
@hamelsmu sir I am new in upwork have sent you a proposal but cant seem to find the option to message you directly https://www.upwork.com/ab/proposals/1811011578134102017 This is the proposal link if you can see to it and accept it then i will have a message access to you

**Comment by hamelsmu** [comment]
Actually @amqdn also looks like the timestamps are incorrect.  So don't worry about it,  you can just use this file as a placeholder :) 

Thanks @sharmachaitanya945 for getting this started

**Comment by amqdn** [comment]
Got it!

**Pull request merged**
